---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.100.101"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[reposync::default]
      - recipe[test::default]
    attributes:
      yum:
        epel:
          mirrorlist: http://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
